/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/DmsL15cu9Y7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-[url('/omikuji-bg.jpg')] bg-cover bg-center">
      <div className="bg-white rounded-lg shadow-lg p-8 w-full max-w-md">
        <div className="flex flex-col items-center">
          <h1 className="text-3xl font-bold mb-4">おみくじ</h1>
          <div className="relative w-full h-[200px] mb-6">
            <div className="absolute top-0 left-0 w-full h-full bg-[url('/omikuji-scroll.png')] bg-no-repeat bg-contain animate-scroll" />
            <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-4xl font-bold text-white">
              <span id="fortune-level">大吉</span>
            </div>
          </div>
          <Button
            className="w-full mb-4"
            onClick={() => {
              const fortuneLevels = ["\u5927\u5409", "\u5409", "\u4E2D\u5409", "\u5C0F\u5409", "\u672B\u5409", "\u51F6"]
              const randomIndex = Math.floor(Math.random() * fortuneLevels.length)
              const fortuneLevel = fortuneLevels[randomIndex]
              document.getElementById("fortune-level").textContent = fortuneLevel
            }}
          >
            おみくじを引く
          </Button>
          <div className="prose text-center">
            <p id="fortune-advice">今日は良い一日になりそうです。新しいことにチャレンジしてみましょう。</p>
          </div>
          <div className="flex justify-center mt-4">
            <Button
              variant="outline"
              className="mr-2"
              onClick={() => {
                const fortuneLevel = document.getElementById("fortune-level").textContent
                const fortuneAdvice = document.getElementById("fortune-advice").textContent
                const imageUrl = `/omikuji-${fortuneLevel.toLowerCase()}.png`
                const shareUrl = `https://example.com/omikuji?level=${fortuneLevel}&advice=${encodeURIComponent(
                  fortuneAdvice,
                )}`
              }}
            >
              保存
            </Button>
            <Button
              variant="outline"
              onClick={() => {
                const fortuneLevel = document.getElementById("fortune-level").textContent
                const fortuneAdvice = document.getElementById("fortune-advice").textContent
                const shareUrl = `https://example.com/omikuji?level=${fortuneLevel}&advice=${encodeURIComponent(
                  fortuneAdvice,
                )}`
              }}
            >
              共有
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
